import { GoogleGenerativeAI } from "@google/generative-ai";
import axios from "axios";

export const generateSupremeLearning = async (req, res) => {
  try {
    // Verify API keys are loaded
    if (!process.env.GEMINI_API_KEY) {
      console.error("❌ GEMINI_API_KEY not found in environment variables");
      return res.status(500).json({
        error: "API configuration error",
        message: "GEMINI_API_KEY is not configured",
      });
    }

    if (!process.env.YOUTUBE_API_KEY) {
      console.error("❌ YOUTUBE_API_KEY not found in environment variables");
      return res.status(500).json({
        error: "API configuration error",
        message: "YOUTUBE_API_KEY is not configured",
      });
    }

    const { subject, topic, difficulty, examPreparing } = req.body;

    if (!subject || !topic) {
      return res.status(400).json({ error: "Subject and topic are required" });
    }

    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    // Step 1: Generate YouTube video search keywords using Gemini
    const videoPrompt = `You are an expert learning resource curator. Based on the topic below, generate search keywords to find the BEST YouTube educational video.

Subject: ${subject}
Topic: ${topic}
Difficulty Level: ${difficulty}
Exam Preparing For: ${examPreparing}

Think of specific, searchable keywords that would find high-quality educational videos on YouTube.

Respond with ONLY valid JSON (no markdown, no extra text):
{
  "searchKeywordsPrimary": "Most effective search keywords (e.g., 'Photosynthesis explained Khan Academy' or 'Thermodynamics tutorial')",
  "searchKeywordsSecondary": "Alternative keywords if primary doesn't work",
  "description": "Why these search terms will find excellent videos on this topic"
}`;

    const videoResponse = await model.generateContent(videoPrompt);
    let videoResponseText = videoResponse.response.text();
    
    console.log("✅ Video keywords generated by Gemini");
    
    videoResponseText = videoResponseText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();

    let videoKeywords = {};
    try {
      const jsonMatch = videoResponseText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        videoKeywords = JSON.parse(jsonMatch[0]);
        console.log("✅ Keywords parsed:", videoKeywords.searchKeywordsPrimary);
      }
    } catch (e) {
      console.error("⚠️ Error parsing keywords:", e.message);
      videoKeywords = {
        searchKeywordsPrimary: `${subject} ${topic} tutorial`,
        searchKeywordsSecondary: `${topic} explained`,
        description: "Educational video on this topic",
      };
    }

    // Step 2: Search YouTube using the API
    console.log("🔍 Searching YouTube for videos...");
    const youtubeSearchUrl = "https://www.googleapis.com/youtube/v3/search";
    
    let youtubeVideos = [];
    try {
      const searchResponse = await axios.get(youtubeSearchUrl, {
        params: {
          key: process.env.YOUTUBE_API_KEY,
          part: "snippet",
          q: videoKeywords.searchKeywordsPrimary,
          type: "video",
          maxResults: 5,
          order: "relevance",
          relevanceLanguage: "en",
        },
      });

      youtubeVideos = searchResponse.data.items || [];
      console.log(`✅ Found ${youtubeVideos.length} videos on YouTube`);
    } catch (err) {
      console.error("⚠️ YouTube search error:", err.message);
      // Fall back to secondary keywords if primary fails
      try {
        const fallbackResponse = await axios.get(youtubeSearchUrl, {
          params: {
            key: process.env.YOUTUBE_API_KEY,
            part: "snippet",
            q: videoKeywords.searchKeywordsSecondary,
            type: "video",
            maxResults: 5,
            order: "relevance",
          },
        });
        youtubeVideos = fallbackResponse.data.items || [];
        console.log(`✅ Found ${youtubeVideos.length} videos with secondary keywords`);
      } catch (fallbackErr) {
        console.error("❌ YouTube fallback search also failed:", fallbackErr.message);
      }
    }

    // Get the first video (best match)
    let videoData = {
      videoId: "",
      title: `${topic} - Educational Video`,
      channel: "Educational Channel",
      description: videoKeywords.description || "Learn this topic",
      thumbnail: "",
    };

    if (youtubeVideos.length > 0) {
      const firstVideo = youtubeVideos[0];
      videoData = {
        videoId: firstVideo.id.videoId,
        title: firstVideo.snippet.title,
        channel: firstVideo.snippet.channelTitle,
        description: firstVideo.snippet.description,
        thumbnail: firstVideo.snippet.thumbnails?.high?.url,
      };
      console.log("✅ Top video selected:", videoData.title);
    }

    // Generate comprehensive notes
    const notesPrompt = `You are an expert teacher creating comprehensive study notes. Generate detailed, well-organized notes for the following:

Subject: ${subject}
Topic: ${topic}
Difficulty Level: ${difficulty}
Exam Preparing For: ${examPreparing}

Create notes with:
1. **Key Concepts** - Main ideas and definitions
2. **Detailed Explanation** - In-depth coverage of each concept
3. **Important Points** - Highlight critical information
4. **Formulas/Laws** (if applicable) - Relevant formulas or scientific laws
5. **Examples** - Real-world or practical examples
6. **Common Misconceptions** - Things students often get wrong
7. **Tips for Exam** - How to apply this knowledge in exams
8. **Quick Summary** - Bullet-point overview

Use clear markdown formatting with headers, bullet points, and emphasis. Make it comprehensive but easy to understand.`;

    const notesResponse = await model.generateContent(notesPrompt);
    const notesText = notesResponse.response.text();
    
    console.log("✅ Notes generated successfully");

    // Create YouTube URLs
    const embedUrl = videoData.videoId 
      ? `https://www.youtube.com/embed/${videoData.videoId}`
      : `https://www.youtube.com/results?search_query=${encodeURIComponent(videoKeywords.searchKeywordsPrimary)}`;
    
    const watchUrl = videoData.videoId
      ? `https://www.youtube.com/watch?v=${videoData.videoId}`
      : `https://www.youtube.com/results?search_query=${encodeURIComponent(videoKeywords.searchKeywordsPrimary)}`;

    console.log("✅ Supreme Learning prepared successfully");
    console.log("   Video ID:", videoData.videoId || "Search results");
    console.log("   Video Title:", videoData.title);

    res.status(200).json({
      success: true,
      video: {
        videoId: videoData.videoId,
        title: videoData.title,
        channel: videoData.channel,
        description: videoData.description,
        thumbnail: videoData.thumbnail,
        embedUrl: embedUrl,
        watchUrl: watchUrl,
        searchKeywordsPrimary: videoKeywords.searchKeywordsPrimary,
        searchKeywordsSecondary: videoKeywords.searchKeywordsSecondary,
      },
      notes: notesText,
    });
  } catch (error) {
    console.error("❌ Supreme Learning Error:", error.message);
    console.error("Full error:", error);
    
    // Provide specific error messages for different scenarios
    if (error.message.includes("API key not valid")) {
      return res.status(401).json({
        error: "Invalid API key",
        message: "The Gemini API key is invalid or expired. Please update it in your .env file.",
        debug: process.env.NODE_ENV === "development" ? error.message : undefined,
      });
    }

    if (error.message.includes("API not activated")) {
      return res.status(403).json({
        error: "API not enabled",
        message: "Enable the Generative Language API in your Google Cloud Console",
      });
    }

    res.status(500).json({
      error: "Failed to generate learning materials",
      message: error.message,
      details: process.env.NODE_ENV === "development" ? error.stack : undefined,
    });
  }
};
